
[gemini]
# api_key will be loaded from .env (GEMINI_API_KEY)
primary_model = "models/gemini-2.5-flash-preview-05-20"
small_model = "models/gemini-2.0-flash-001"
multimodal_model = "models/gemini-2.0-flash"
max_output_tokens = 8192
temperature = 0.1 # Adjusted default temperature

[search]
# API keys will be loaded from .env (GOOGLE_SEARCH_API_KEY, GOOGLE_CSE_ID)
primary_engine = "Google" 
fallback_engine = "GoogleScraper" 
num_results = 5

[browser]
headless = false
disable_security = true

[sandbox]
use_sandbox = false
